const treks = [
  {
    id: 1,
    trekName: "Ratangad Fireflies Trek & Sandhan Valley",
    trekStartDate: "2024-06-01",
    trekEndDate: "2024-06-02",
    type: "Himalayan Treks",
  },
  {
    id: 2,
    trekName: "Kalsubai Fireflies Trek & Sandhan Valley",
    trekStartDate: "2024-06-08",
    trekEndDate: "2024-06-09",
    type: "Sahyadri Treks",
  },
  {
    id: 3,
    trekName: "Kedarnath Trek",
    trekStartDate: "2024-06-13",
    trekEndDate: "2024-06-18",
    type: "Backpacking Treks",
  },
  {
    id: 4,
    trekName: "Kalsubai Monsoon Trek & Sandhan Valley",
    trekStartDate: "2024-06-15",
    trekEndDate: "2024-06-16",
    type: "Packages",
  },
  {
    id: 5,
    trekName: "Sondai Fort Trek & Matheran",
    trekStartDate: "2024-06-22",
    trekEndDate: "2024-06-23",
    type: "Himalayan Treks",
  },
  {
    id: 6,
    trekName: "Harishchandragad Monsoon Trek",
    trekStartDate: "2024-06-29",
    trekEndDate: "2024-06-30",
    type: "Sahyadri Treks",
  },
  {
    id: 7,
    trekName: "Kothaligad Trek & Matheran",
    trekStartDate: "2024-06-29",
    trekEndDate: "2024-06-30",
    type: "Backpacking Treks",
  },
  {
    id: 8,
    trekName: "Ratangad Monsoon Trek & Sandhan Valley",
    trekStartDate: "2024-07-06",
    trekEndDate: "2024-07-07",
    type: "Packages",
  },
  {
    id: 9,
    trekName: "Kalsubai Monsoon Trek & Sandhan Valley",
    trekStartDate: "2024-07-13",
    trekEndDate: "2024-07-14",
    type: "Himalayan Treks",
  },
  {
    id: 10,
    trekName: "Seven Sister's Hill Trek",
    trekStartDate: "2024-07-14",
    trekEndDate: "2024-07-14",
    type: "Sahyadri Treks",
  },
  {
    id: 11,
    trekName: "Harishchandragad Monsoon Trek",
    trekStartDate: "2024-07-20",
    trekEndDate: "2024-07-21",
    type: "Backpacking Treks",
  },
  {
    id: 12,
    trekName: "Kalsubai Monsoon Trek & Sandhan Valley",
    trekStartDate: "2024-07-27",
    trekEndDate: "2024-07-28",
    type: "Packages",
  },
];

export default treks;

export const productData = {
  id: "1000",
  code: "f230fh0g3",
  name: "Bamboo Watch",
  description: "Product Description",
  image: "bamboo-watch.jpg",
  price: 65,
  category: "Accessories",
  quantity: 24,
  inventoryStatus: "INSTOCK",
  rating: 5,
};
